name: Daily LINE Bot Messages

on:
  schedule:
    - cron: '0 3,12,20 * * *'  # JSTで12:00, 21:00, 翌5:00に実行
  workflow_dispatch:

jobs:
  send-messages:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.js セットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 依存関係をインストール
        run: npm install

      - name: 環境変数を設定（Secretsから）
        env:
          CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: node cron.js
