- name: morning-message
  schedule: '0 1 * * *'     # JST 10:00
  command: 'node cron.js'

- name: afternoon-message
  schedule: '0 5 * * *'     # JST 14:00
  command: 'node cron.js'

- name: evening-message
  schedule: '0 9 * * *'     # JST 18:00
  command: 'node cron.js'
